#!/bin/sh

set -e

err() {
	xitval=$1
	shift
	echo "$*" 1>&2
	exit $exitval
}

: ${distdir="/usr/local/cbsd"}
# MAIN
if [ -z "${workdir}" ]; then
	[ -z "${cbsd_workdir}" ] && . /etc/rc.conf
	[ -z "${cbsd_workdir}" ] && exit 0
	workdir="${cbsd_workdir}"
fi

set -e
. ${workdir}/cmd.subr
. ${distdir}/cbsd.conf
. ${distdir}/tools.subr
. ${subr}
set +e

_MYDIR=$(dirname `realpath $0`)
[ ! -f "${_MYDIR}/cpr.inc" ] && err 1 "Missed cpr.inc in ${_MYDIR}"
. ${_MYDIR}/cpr.inc

# MAIN()
while getopts "v:a:m:s:" opt; do
	case "${opt}" in
		v) _VER="${OPTARG}" ;;
		a) oarch="${OPTARG}" ;;
		m) _MASTERLINK="${OPTARG}" ;;
		s) STABLE="${OPTARG}" ;;
		*)  usage ;;
	esac
	shift $(($OPTIND - 1))
done

. ${_MYDIR}/build.inc
[ -z "${_MASTERLINK}" ] && err 1 "-m is mandatory"
_SLAVELINK="${_MASTERLINK}-slave"
[ -z "${_VER}" ] && err 1 "Give me version, e.g: -v 11.2"
_PATH="${_DOCROOTPKGBASE}/${arch}/${_VER}"
/usr/local/cbsd/misc/symlink_changer -p ${_PATH} -r "${_MASTERLINK}-1 ${_MASTERLINK}-2" -s ${_SLAVELINK} -m ${_MASTERLINK} -a next
